# docs: https://semantic-release.gitbook.io/semantic-release/usage/plugins
plugins:
  - - "@semantic-release/commit-analyzer"
    - parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING

  # this is important to prepare the version
  # and to tell "Jenkins" that we are ready to release
  - - "@semantic-release/exec"
    - verifyReleaseCmd: printf "BUILD_VERSION=${nextRelease.version}\nRELEASE_CHANNEL=${nextRelease.channel}" > .VERSION

branches:
  - name: "+([0-9])?(.{+([0-9]),x}).x"
    channel: stable
  - name: "master"
    channel: stable
  - name: "main"
    channel: stable

  - name: "next"
    channel: next
  - name: "next-major"
    channel: next

  - name: "beta"
    channel: "beta"
    prerelease: true
  - name: "alpha"
    channel: "alpha"
    prerelease: true
