# ID to identify this project in Sonar
sonar.projectKey=goapp-utils
# Common name to group it into a portfolio
sonar.projectName=splunk
# Specify all files to parse
sonar.sources=.
# Exclude unit tests from Sonar analyse
sonar.exclusions=**/*_test.go
